### ISSUE TITLE
Frequent Crashes with Ollama on ARC770 and i7-14700K

### ISSUE THREAD

**Issue by sirlegendary** [intel-analytics/ipex-llm#12555]
## Description
Ollama keeps crashing on my system when I attempt to run models or after interacting with them for 1-2 prompts. Even using q4_K_M, which I understand is designed to be resource-efficient, the crashes persist.

**Examples of Crashing Models:**
* `llama3.2:3b-instruct-q4_K_M`: Crashes after 1-2 prompts.
* `qwen2.5-coder:3b-instruct-q4_K_M`: Also crashes after a few prompts.
**Models That Do Not Crash:**
* `gemma:2b-instruct-q5_K_M`: Runs without issues but is not suitable for my needs.

Additionally, I am unable to run `sycl-ls` to troubleshoot further. When I attempt it, I receive:
```
bash: sycl-ls: command not found
```

## Environment
* GPU: Intel ARC770 (16GB VRAM)
* CPU: Intel i7-14700K
* RAM: 64GB
* OS: Ubuntu 22.04.3 LTS
* Ollama Version:  0.4.6-ipexllm-20241214

## Steps to Reproduce

* Dockerfile:
```
FROM docker.io/intelanalytics/ipex-llm-inference-cpp-xpu:latest

ENV ZES_ENABLE_SYSMAN=1
ENV OLLAMA_HOST=0.0.0.0:11434
ENV OLLAMA_KEEP_ALIVE=3600
ENV DEVICE=Arc

RUN mkdir -p /llm/ollama; \
    cd /llm/ollama; \
    init-ollama;

ENV LD_LIBRARY_PATH=".:$LD_LIBRARY_PATH"

WORKDIR /llm/ollama

ENTRYPOINT ["./ollama", "serve"]
```

* docker-compose file:
```
version: "3.9"
services:
  ollama-intel-gpu:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ollama-intel-gpu
    image: ollama-intel-gpu:latest
    restart: always
    devices:
      - /dev/dri:/dev/dri
      - /dev/dxg:/dev/dxg
    volumes:
      - /usr/lib/wsl:/usr/lib/wsl
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ollama-intel-gpu:/root/.ollama
    environment:
      - DISPLAY=${DISPLAY}
      - PATH=/llm/ollama:$PATH
volumes:
  ollama-intel-gpu: {}
```
* Exec into container `podman exec -it ollama-intel-gpu /bin/bash `
* Run Ollama with `llama3.2:3b-instruct-q4_K_M` or `qwen2.5-coder:3b-instruct-q4_K_M`.
* Interact with the model (1-2 prompts).
* Observe a crash.

## Logs
[ollama_intel_gpu_logs.txt](https://github.com/user-attachments/files/18150095/ollama_intel_gpu_logs.txt)
[ollama_intel_gpu_2_logs.txt](https://github.com/user-attachments/files/18150096/ollama_intel_gpu_2_logs.txt)
